name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Explicitly grant write permission to contents (needed for pushing changes)

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install latest pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install
        
      - name: Build project
        run: pnpm run build

      - name: Commit changes (if any)
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git add .
          # Kiểm tra xem có thay đổi nào cần commit không
          if [[ $(git status --porcelain) ]]; then
            git commit -m "Deploy to GitHub Pages"
          else
            echo "No changes to commit"
          fi

      - name: Push changes
        run: |
          git push https://github-actions:${{ secrets.GH_TOKEN }}@github.com/vuducthang1410/UmijsAndSupabaseAppChat.git
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
